name: "Deploy Helix Package"
description: "Builds and publishes a new version of a HELIX Package"

inputs:
  access_token:
    description: "Access token for authentication. Can be generated on the HELIX Hub: Account -> Access Tokens."
    required: true
  package_path:
    description: "Path of the package to upload. Omit this to default to `.`."
    required: false
    default: "."

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install jq
      shell: bash
      run: sudo apt-get install -y jq

    - name: Zip repository
      shell: bash
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
        PACKAGE_PATH: ${{ inputs.path }}
      run: |
        mkdir $PACKAGE_NAME
        cp $PACKAGE_PATH/Package.toml $PACKAGE_NAME/

        # Ensure folders exist before copying to prevent errors
        mkdir -p $PACKAGE_NAME/Client && cp -r $PACKAGE_PATH/Client/* $PACKAGE_NAME/Client/
        mkdir -p $PACKAGE_NAME/Server && cp -r $PACKAGE_PATH/Server/* $PACKAGE_NAME/Server/
        mkdir -p $PACKAGE_NAME/Shared && cp -r $PACKAGE_PATH/Shared/* $PACKAGE_NAME/Shared/

        zip -r main.zip $PACKAGE_NAME

    - name: Request upload URL
      id: presigned_url
      shell: bash
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
      run: |
        response=$(curl --location "https://api.helixgame.com/v1/packages/upload/${PACKAGE_NAME}" \
          --header "Token: ${ACCESS_TOKEN}")
        echo "Response: $response"
        code=$(echo $response | jq -r '.code')
        message=$(echo $response | jq -r '.message')
        if [ "$code" != "0" ]; then
          if [ "$message" == "package corrupted" ]; then
            echo "Error: Make sure you've created this package on the HELIX Hub first: https://hub.helixgame.com/creations/packages"
          else
            echo "Error: Server returned error code $code with message '$message'"
          fi
          exit 1
        fi
        upload_url=$(echo $response | jq -r '.payload.upload_url')
        package_url=$(echo $response | jq -r '.payload.package_url')
        echo "upload_url=$upload_url" >> $GITHUB_ENV
        echo "package_url=$package_url" >> $GITHUB_ENV
        echo "upload_url=$upload_url"
        echo "package_url=$package_url"

    - name: Upload zip file
      shell: bash
      env:
        UPLOAD_URL: ${{ env.upload_url }}
      run: |
        echo "Uploading to: ${UPLOAD_URL}"
        curl --location --request PUT "${UPLOAD_URL}" \
          --header "Content-Type: application/zip" \
          --data-binary "@main.zip"

    - name: Finish upload
      shell: bash
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
        PACKAGE_URL: ${{ env.package_url }}
      run: |
        curl --location 'https://api.helixgame.com/v1/packages/upload/finish' \
          --header "Content-Type: application/json" \
          --header "Token: ${ACCESS_TOKEN}" \
          --data "{\"url\": \"${PACKAGE_URL}\",\"name\": \"${PACKAGE_NAME}\"}"
