name: 'Deploy Helix Package'
description: 'Uploads a Helix automatically'
inputs:
  access_token:
    description: 'Access token for authentication. Can be generated at Account -> Settings'
    required: true
    type: string
  package_name:
    description: 'Name of the package to upload. Make sure you already have this package created'
    required: true
    type: string
outputs: {}
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Zip repository
      run: zip -r main.zip .

    - name: Request presigned URL
      id: presigned_url
      shell: bash
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
      run: |
        response=$(curl --location "https://api.helixgame.com/v1/packages/upload/${PACKAGE_NAME}" \
          --header "Token: ${ACCESS_TOKEN}")
        echo "{upload_url}={$(echo $response | jq -r '.payload.upload_url')}" >> $GITHUB_OUTPUT
        echo "{package_url}={$(echo $response | jq -r '.payload.package_url')}" >> $GITHUB_OUTPUT

    - name: Upload zip file
      run: |
        curl --location --request PUT "${{ steps.presigned_url.outputs.upload_url }}" \
          --header "Content-Type: application/zip" \
          --data-binary "@main.zip"

    - name: Finish upload
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
        PACKAGE_URL: ${{ steps.presigned_url.outputs.package_url }}
      run: |
        curl --location 'https://api.helixgame.com/v1/packages/upload/finish' \
          --header "Content-Type: application/json" \
          --header "Token: ${ACCESS_TOKEN}" \
          --data "{\"url\": \"${PACKAGE_URL}\",\"name\": \"${PACKAGE_NAME}\"}"

