name: 'Deploy Helix Package'
description: 'Builds and publishes a new version of a HELIX Package'
inputs:
  access_token:
    description: 'Access token for authentication. Can be generated on the HELIX Hub: Account -> Access Tokens'
    required: true
    type: string
  package_name:
    description: 'Name of the package to upload. Make sure you have already created this package in the HELIX Hub or Studio'
    required: true
    type: string
outputs: {}
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      shell: bash
      run: sudo apt-get install -y jq

    - name: Remove .files
      shell: bash
      run: |
        rm -rf .git
        rm -rf .github

    - name: Zip repository
      shell: bash
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        mkdir $PACKAGE_NAME
        mv * $PACKAGE_NAME || true
        zip -r main.zip $PACKAGE_NAME

    - name: Request upload URL
      id: presigned_url
      shell: bash
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
      run: |
        response=$(curl --location "https://api.helixgame.com/v1/packages/upload/${PACKAGE_NAME}" \
          --header "Token: ${ACCESS_TOKEN}")
        echo "Response: $response"
        upload_url=$(echo $response | jq -r '.payload.upload_url')
        package_url=$(echo $response | jq -r '.payload.package_url')
        echo "upload_url=$upload_url" >> $GITHUB_ENV
        echo "package_url=$package_url" >> $GITHUB_ENV
        echo "upload_url=$upload_url"
        echo "package_url=$package_url"

    - name: Upload zip file
      shell: bash
      env:
        UPLOAD_URL: ${{ env.upload_url }}
      run: |
        echo "Uploading to: ${UPLOAD_URL}"
        curl --location --request PUT "${UPLOAD_URL}" \
          --header "Content-Type: application/zip" \
          --data-binary "@main.zip"

    - name: Finish upload
      shell: bash
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
        ACCESS_TOKEN: ${{ inputs.access_token }}
        PACKAGE_URL: ${{ env.package_url }}
      run: |
        curl --location 'https://api.helixgame.com/v1/packages/upload/finish' \
          --header "Content-Type: application/json" \
          --header "Token: ${ACCESS_TOKEN}" \
          --data "{\"url\": \"${PACKAGE_URL}\",\"name\": \"${PACKAGE_NAME}\"}"
